Function to convert manifest.json to renv.lock
rstudio/renv pull request #707
Opened 2021-04-06 22:26 UTC by JosiahParry

Overview: 

- Many customers are trying to adopt {renv} to improve their development process. Customers will deploy a piece of content to RSC using push button deployment. They'll come back to the project and learn that their environment is wrecked. The RSC content bundle contains the manifest.json file generated from rsconnect. Converting that to an renv.lock file is not straight forward. This pull request creates functionality to take the manifest.json file and convert it to

## Changes: 

- Adds a `version()` method to the internal `lockfile` R6 object
- Creates new function `rsc_manifest_to_renv_lock()` which takes a manifest as input and produces an renv.lockfile.

2021-04-06 23:07 UTC, kevinushey requested changes
Thanks for the PR! I'd prefer to leave this as an unexported function for now (we could document and allow users to call it with `renv:::` explicitly), since this function is fairly specific + coupled to RSC.

2021-04-06 23:07 UTC, kevinushey commented on R/manifest-convert.R
> +rsc_manifest_to_renv_lock <- function(manifest = NULL, lockfile = NA) {
Could we make this an un-exported function called e.g. `renv_lockfile_from_manifest()`?

2021-04-06 23:07 UTC, kevinushey commented on R/manifest-convert.R
> +  cat("* Reading manifest.json...\n")
Use `vwritef()` (if you think the user should be able to disable logging) or `writef()` instead.

2021-04-06 23:07 UTC, kevinushey commented on R/manifest-convert.R
> +  if (!file.exists(lockfile %&&% "") & !is.na(lockfile)) {
```suggestion
  if (!is.na(lockfile) && file.exists(lockfile)) {
  if (!file.exists(lockfile %&&% "") & !is.na(lockfile)) {
```

2021-04-06 23:07 UTC, kevinushey commented on R/manifest-convert.R
> +  cat("* Parsing dependencies...\n")
Same as above.

2021-04-06 23:07 UTC, kevinushey commented on R/manifest-convert.R
> +  } else{
```suggestion
  } else {
```

2021-04-06 23:07 UTC, kevinushey commented on NAMESPACE
> +export(rsc_manifest_to_renv_lock)
I'd prefer to leave this un-exported.

2021-04-07 13:04 UTC, JosiahParry commented
Thanks, Kevin! The requested changes have been made.

2021-04-07 16:08 UTC, merged

2021-04-07 16:08 UTC, kevinushey commented
Thanks!

2021-04-07 16:15 UTC, JosiahParry commented
No, thank you! :)